namespace PortfolioDev.Application.Helpers.Erros;

public enum CodigoErro
{
	ITEM_NAO_ENCONTRADO,
	OUTRO,
	REGISTRO_NAO_EFETUADO,
	UPDATE_NAO_EFETUADO,
	DELETE_NAO_EFETUADO,
	PERMISSAO_NEGADA,
	USUARIO_DUPLICADO_EMAIL,
	USUARIO_DUPLICADO_USERNAME,
	USUARIO_LOGIN_INVALIDO
}